spring:
  application:
    name: helpdesk
  config:
    import: optional:vault://
  main:
    banner-mode: console
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_ADDR}
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8888 # rest port (in our case grpc over rest)
  error:
    include-message: always
    include-binding-errors: always
